.TH evilurl 1 "January 01, 2024" "evilurl(1)"

.SH NAME
evilurl \- Analyze domains for the risk of IDN homograph attacks

.SH SYNOPSIS
.B evilurl
[\fIOPTIONS\fR] \fIdomain\fR
.B evilurl
\fB\-f \fIfile_path\fR

.SH DESCRIPTION
\fBEvilURL\fR is a cybersecurity tool designed to safeguard against IDN homograph attacks by identifying visually similar domain names.

.SH OPTIONS
.TP
.B \-f \fIfile_path\fR
Analyze domains listed in a file.

.TP
.B \-d
Show only the generated homograph domains without additional information.

.SH EXAMPLES
.B evilurl example.com
.B evilurl \-f domains.txt
.B evilurl \-d example.com

.SH AUTHOR
Written by @glaubermagal.

.SH REPORTING BUGS
Report bugs to: https://github.com/glaubermagal/evilurl/issues

.SH SEE ALSO
More information can be found at: https://github.com/glaubermagal/evilurl

.SH COPYRIGHT
Copyright (c) 2024 Glauber

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
