name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install build dependencies
      run: python -m pip install --upgrade pip setuptools wheel twine pex

    - name: Build executable with dependencies
      run: pex . -o evilurl -r pandas -e evilurl:main

    - name: Build the package (for normal installation method as well)
      run: python setup.py sdist bdist_wheel

    - name: Publish distributions
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/* -u __token__ -p $PYPI_API_TOKEN --verbose
        twine upload evilurl -u __token__ -p $PYPI_API_TOKEN --verbose # Uploads the standalone executable.
